run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m
  tests: true

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters:
  enable:
    # Sorted alphabetically.
    - bodyclose
    - deadcode
    - depguard
    - errcheck
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - godot
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck

linters-settings:
  errcheck:
    exclude-functions:
      - '(github.com/go-kit/log.Logger).Log'
  lll:
    line-length: 140
  funlen:
    lines: 120
    statements: 45
  gocognit:
    min-complexity: 40
